// tslint:disable
/**
 * Genies Mobile API
 * Genies Composer server.
 *
 * OpenAPI spec version: 1.7.3
 *
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from './api';
export * from './configuration';
