import axios from 'axios';
import Logger from 'shared/logger';

export enum EndpointName {
  GET_GEAR_BY_ID = 'GET_GEAR_BY_ID',
  UPDATE_GEAR = 'UPDATE_GEAR',
  GET_GEAR_LIST_ADMIN = 'GET_GEAR_LIST_ADMIN',
  GET_THINGS_ADMIN = 'GET_THINGS_ADMIN',
  DELETE_THINGS_ADMIN = 'DELETE_THINGS_ADMIN',
  GET_TRAITS = 'GET_TRAITS',
  GET_USER_TRAIT_PROFILE = 'GET_USER_TRAIT_PROFILE',
  SET_TRAIT_SOCRE = 'SET_TRAIT_SOCRE',
  RESET_TRAIT_PROFILE = 'RESET_TRAIT_PROFILE',
  GET_TRAIT_PROGRESS = 'GET_TRAIT_PROGRESS',
  FORCE_ADD_HARD_CURRENCY = 'FORCE_ADD_HARD_CURRENCY',
  GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY',
  GET_HARD_CURRENCY_PRODUCTS = 'GET_HARD_CURRENCY_PRODUCTS',
  UPDATE_HARD_CURRENCY_PRODUCT = 'UPDATE_HARD_CURRENCY_PRODUCT',
  ADD_HARD_CURRENCY_PRODUCT = 'ADD_HARD_CURRENCY_PRODUCT',
  UPSERT_HC_PRODUCT_SKU_MAPPING = 'UPSERT_HC_PRODUCT_SKU_MAPPING',
  UPSERT_HC_PRODUCT_METADATA = 'UPSERT_HC_PRODUCT_METADATA',
  GET_ALL_HC_PRODUCT_METADATA = 'GET_ALL_HC_PRODUCT_METADATA',
  GET_ALL_SOFT_CURRENCY_PRODUCTS = 'GET_ALL_SOFT_CURRENCY_PRODUCTS',
  UPDATE_SOFT_CURRENCY_PRODUCT = 'UPDATE_SOFT_CURRENCY_PRODUCT',
  ADD_SOFT_CURRENCY_PRODUCT = 'ADD_SOFT_CURRENCY_PRODUCT',
  DELETE_SOFT_CURRENCY_PRODUCT = 'DELETE_SOFT_CURRENCY_PRODUCT',
  GET_ALL_CURRENCIES_FOR_OWNER = 'GET_ALL_CURRENCIES_FOR_OWNER',
  UPSERT_SOFT_CURRENCY = 'UPSERT_SOFT_CURRENCY',
  DELETE_SOFT_CURRENCY = 'DELETE_SOFT_CURRENCY',
  GET_ADMIN_USER_INVENTORY = 'GET_ADMIN_USER_INVENTORY',
  CREATE_METADATA_STORE = 'CREATE_METADATA_STORE',
  GET_METADATA_TAG = 'GET_METADATA_TAG',
  SET_METADATA_TAG = 'SET_METADATA_TAG',
  CREATE_ASSET_SUPPLY = 'CREATE_ASSET_SUPPLY',
  GET_METADATA_STORE = 'GET_METADATA_STORE',
  MINT_ASSET = 'MINT_ASSET',
  BURN_ASSET_INSTANCE = 'BURN_ASSET_INSTANCE',
  DELETE_ASSETS = 'DELETE_ASSETS',
  // V2 Inventory Endpoints (Real endpoints from swagger)
  GET_INVENTORY_V2_ANIMATION_LIBRARY = 'GET_INVENTORY_V2_ANIMATION_LIBRARY',
  GET_INVENTORY_V2_AVATAR_DNA = 'GET_INVENTORY_V2_AVATAR_DNA',
  GET_INVENTORY_V2_AVATAR_EYES = 'GET_INVENTORY_V2_AVATAR_EYES',
  GET_INVENTORY_V2_AVATAR_FLAIR = 'GET_INVENTORY_V2_AVATAR_FLAIR',
  GET_INVENTORY_V2_AVATAR_MAKEUP = 'GET_INVENTORY_V2_AVATAR_MAKEUP',
  GET_INVENTORY_V2_COLOR_PRESETS = 'GET_INVENTORY_V2_COLOR_PRESETS',
  GET_INVENTORY_V2_IMAGE_LIBRARY = 'GET_INVENTORY_V2_IMAGE_LIBRARY',
  GET_INVENTORY_V2_MODEL_LIBRARY = 'GET_INVENTORY_V2_MODEL_LIBRARY',
  GET_INVENTORY_V2_AVATAR = 'GET_INVENTORY_V2_AVATAR',
  GET_INVENTORY_V2_DECOR = 'GET_INVENTORY_V2_DECOR',
  GET_INVENTORY_V2_GEAR = 'GET_INVENTORY_V2_GEAR',
  // Default Items Endpoints
  GET_DEFAULT_GEAR = 'GET_DEFAULT_GEAR',
  GET_DEFAULT_DECOR = 'GET_DEFAULT_DECOR',
  GET_DEFAULT_AVATAR = 'GET_DEFAULT_AVATAR',
  GET_DEFAULT_AVATAR_DNA = 'GET_DEFAULT_AVATAR_DNA',
  GET_DEFAULT_AVATAR_MAKEUP = 'GET_DEFAULT_AVATAR_MAKEUP',
  GET_DEFAULT_AVATAR_FLAIR = 'GET_DEFAULT_AVATAR_FLAIR',
  GET_DEFAULT_AVATAR_EYES = 'GET_DEFAULT_AVATAR_EYES',
  GET_DEFAULT_COLOR_PRESETS = 'GET_DEFAULT_COLOR_PRESETS',
  GET_DEFAULT_IMAGE_LIBRARY = 'GET_DEFAULT_IMAGE_LIBRARY',
  GET_DEFAULT_ANIMATION_LIBRARY = 'GET_DEFAULT_ANIMATION_LIBRARY',
  GET_DEFAULT_MODEL_LIBRARY = 'GET_DEFAULT_MODEL_LIBRARY',
  // Metadata Store Manager Endpoints
  GET_ALL_METADATA_STORES = 'GET_ALL_METADATA_STORES',
  CREATE_DEFAULT_CLOSET_NAMESPACE = 'CREATE_DEFAULT_CLOSET_NAMESPACE',
  CREATE_DEFAULT_ITEM = 'CREATE_DEFAULT_ITEM',
  UPDATE_METADATA_TAG = 'UPDATE_METADATA_TAG',
  // Inventory Moderation Endpoints
  CREATE_MODERATION_METADATA_STORE = 'CREATE_MODERATION_METADATA_STORE',
  CREATE_ASSET_STATUS_METADATA_STORE = 'CREATE_ASSET_STATUS_METADATA_STORE',
  UPDATE_ASSET_MODERATION_STATUS = 'UPDATE_ASSET_MODERATION_STATUS',
  UPDATE_ASSET_LIFECYCLE_STATUS = 'UPDATE_ASSET_LIFECYCLE_STATUS',
  GET_ASSETS_BY_MODERATION_STATUS = 'GET_ASSETS_BY_MODERATION_STATUS',
  GET_ASSET_MODERATION_STATUS = 'GET_ASSET_MODERATION_STATUS',
  SUBMIT_ASSET_FOR_REVIEW = 'SUBMIT_ASSET_FOR_REVIEW',
}

export const EndpointMethodMap = {
  GET_GEAR_BY_ID: 'GET',
  UPDATE_GEAR: 'PATCH',
  GET_GEAR_LIST_ADMIN: 'GET',
  GET_THINGS_ADMIN: 'GET',
  DELETE_THINGS_ADMIN: 'POST',
  GET_TRAITS: 'GET',
  GET_USER_TRAIT_PROFILE: 'GET',
  SET_TRAIT_SOCRE: 'PATCH',
  RESET_TRAIT_PROFILE: 'DELETE',
  GET_TRAIT_PROGRESS: 'GET',
  FORCE_ADD_HARD_CURRENCY: 'PATCH',
  GET_TRANSACTION_HISTORY: 'GET',
  GET_HARD_CURRENCY_PRODUCTS: 'GET',
  UPDATE_HARD_CURRENCY_PRODUCT: 'PATCH',
  ADD_HARD_CURRENCY_PRODUCT: 'POST',
  UPSERT_HC_PRODUCT_SKU_MAPPING: 'POST',
  UPSERT_HC_PRODUCT_METADATA: 'POST',
  GET_ALL_HC_PRODUCT_METADATA: 'GET',
  GET_ALL_SOFT_CURRENCY_PRODUCTS: 'GET',
  UPDATE_SOFT_CURRENCY_PRODUCT: 'PATCH',
  ADD_SOFT_CURRENCY_PRODUCT: 'POST',
  DELETE_SOFT_CURRENCY_PRODUCT: 'DELETE',
  GET_ALL_CURRENCIES_FOR_OWNER: 'GET',
  UPSERT_SOFT_CURRENCY: 'POST',
  DELETE_SOFT_CURRENCY: 'DELETE',
  GET_ADMIN_USER_INVENTORY: 'GET',
  CREATE_METADATA_STORE: 'POST',
  GET_METADATA_TAG: 'GET',
  SET_METADATA_TAG: 'POST',
  CREATE_ASSET_SUPPLY: 'POST',
  GET_METADATA_STORE: 'GET',
  MINT_ASSET: 'POST',
  BURN_ASSET_INSTANCE: 'DELETE',
  DELETE_ASSETS: 'POST',
  // V2 Inventory Endpoint Methods (Real endpoints)
  GET_INVENTORY_V2_ANIMATION_LIBRARY: 'GET',
  GET_INVENTORY_V2_AVATAR_DNA: 'GET',
  GET_INVENTORY_V2_AVATAR_EYES: 'GET',
  GET_INVENTORY_V2_AVATAR_FLAIR: 'GET',
  GET_INVENTORY_V2_AVATAR_MAKEUP: 'GET',
  GET_INVENTORY_V2_COLOR_PRESETS: 'GET',
  GET_INVENTORY_V2_IMAGE_LIBRARY: 'GET',
  GET_INVENTORY_V2_MODEL_LIBRARY: 'GET',
  GET_INVENTORY_V2_AVATAR: 'GET',
  GET_INVENTORY_V2_DECOR: 'GET',
  GET_INVENTORY_V2_GEAR: 'GET',
  // Default Items Endpoint Methods
  GET_DEFAULT_GEAR: 'GET',
  GET_DEFAULT_DECOR: 'GET',
  GET_DEFAULT_AVATAR: 'GET',
  GET_DEFAULT_AVATAR_DNA: 'GET',
  GET_DEFAULT_AVATAR_MAKEUP: 'GET',
  GET_DEFAULT_AVATAR_FLAIR: 'GET',
  GET_DEFAULT_AVATAR_EYES: 'GET',
  GET_DEFAULT_COLOR_PRESETS: 'GET',
  GET_DEFAULT_IMAGE_LIBRARY: 'GET',
  GET_DEFAULT_ANIMATION_LIBRARY: 'GET',
  GET_DEFAULT_MODEL_LIBRARY: 'GET',
  // Metadata Store Manager Endpoint Methods
  GET_ALL_METADATA_STORES: 'GET',
  CREATE_DEFAULT_CLOSET_NAMESPACE: 'POST',
  CREATE_DEFAULT_ITEM: 'POST',
  UPDATE_METADATA_TAG: 'PATCH',
  // Inventory Moderation Endpoints
  CREATE_MODERATION_METADATA_STORE: 'POST',
  CREATE_ASSET_STATUS_METADATA_STORE: 'POST',
  UPDATE_ASSET_MODERATION_STATUS: 'PUT',
  UPDATE_ASSET_LIFECYCLE_STATUS: 'PUT',
  GET_ASSETS_BY_MODERATION_STATUS: 'GET',
  GET_ASSET_MODERATION_STATUS: 'GET',
  SUBMIT_ASSET_FOR_REVIEW: 'PUT',
};

/**
 * API call to request from the shim social admin endpoints
 * @param endpoint that shim is calling
 * @param params query params for the request
 * @param data any body data to pass
 * @param options additional options including headers
 * @returns
 */
export default async function callShimAdmin(
  endpoint: EndpointName,
  params: any = null,
  data: any = null,
  options: any = null,
): Promise<any> {
  try {
    const res = await axios({
      method: EndpointMethodMap[endpoint],
      baseURL: window.location.origin,
      url: '/api/shim',
      data: data,
      params: {
        endpoint,
        ...params,
      },
      ...options,
    });

    // Check if the response data indicates an error from the API
    if (
      res.data &&
      typeof res.data === 'object' &&
      res.data.message &&
      (res.data.message.includes('status code') ||
        res.data.message.includes('error'))
    ) {
      Logger.getInstance().error(`API error response: ${res.data.message}`, {
        endpoint,
        params,
        source: 'callShimAdmin',
      });
      throw new Error(res.data.message);
    }

    return Promise.resolve(res.data);
  } catch (error) {
    Logger.getInstance().error(`callShimAdmin error: ${error.message}`, {
      errorMessage: error.message,
      endpoint,
      params,
      source: 'callShimAdmin',
    });
    throw error;
  }
}
