// tslint:disable
/**
 * Genies User API
 * Genies User API
 *
 * OpenAPI spec version: 1.0.8-oas3
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
