export enum ThingVersionStatus {
  PROCESSING = 'PROCESSING',
  UNDERREVIEW = 'UNDERREVIEW',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  ALL = 'ALL',
  APPROVED = 'APPROVED',
}
